DROP TABLE MYBOARD;

CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_MY NOCACHE;

INSERT INTO MYBOARD 
VALUES(SEQ_MY.NEXTVAL, '관리자','스트프링 테스트','SPRING MVC 어렵다..', CURRENT_DATE);

SELECT * FROM MYBOARD;

------------------

DROP TABLE MYMEMBER;

CREATE TABLE MYMEMBER(
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(1000) NOT NULL,
	MEMBERPW VARCHAR2(1000) NOT NULL,
	MEMBERNAME VARCHAR2(1000) NOT NULL
);

CREATE SEQUENCE SEQ_MEMBER NOCACHE;

INSERT INTO MYMEMBER
VALUES(SEQ_MEMBER.NEXTVAL, 'admin','1234','관리자');

SELECT * FROM MYMEMBER;

----------------

CREATE TABLE RESTBOARD(
	RESTNO NUMBER PRIMARY KEY,
	RESTID VARCHAR2(500) NOT NULL,
	RESTPW VARCHAR2(500) NOT NULL,
	RESTNAME VARCHAR2(500) NOT NULL
);

CREATE SEQUENCE RESTNOSEQ NOCACHE;

INSERT INTO RESTBOARD VALUES(RESTNOSEQ.NEXTVAL, 'admin','1234','관리자');

SELECT * FROM RESTBOARD;

---------------------------------

DROP TABLE MYBOARD;

DROP SEQUENCE MYNOSEQ;

CREATE SEQUENCE MYNOSEQ NOCACHE;
CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(500) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD
VALUES(MYNOSEQ.NEXTVAL, 'ADMIN','TEST INSERT','TEST 1234 ABCD',CURRENT_DATE);

SELECT * FROM MYBOARD ORDER BY MYNO DESC;





